version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - VECTOR_STORE_TYPE=chroma
      - CHROMA_PERSIST_DIR=/app/chroma_db
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./chroma_db:/app/chroma_db
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - rag-network

  rag-ui:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
    depends_on:
      - rag-api
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    networks:
      - rag-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge